# Generated by Django 2.1.15 on 2020-04-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_specials',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pluginapp_daily_specials', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='daily_specials')),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Daily Special',
                'verbose_name_plural': 'Daily Specials',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
